name: polls
channels:
  - conda-forge
dependencies:
  - python
  - dash==2.3.1
  - dash-bootstrap-components==0.13
  - plotly
  - pandas
  - numpy
  - taxcalc
  - pip
  - pip:
      - "git+git://github.com/PSLmodels/microdf.git"
      - "git+https://github.com/UBICenter/ubicenter.py"
      - black
      - kaleido
